#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/gson-2.3.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/jeromq-0.3.4.jar:$APPDIR/lib/toxiclibscore.jar:$APPDIR/lib/P2LX.jar:$APPDIR/lib/dreamscape.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/minim.jar:$APPDIR/lib/tritonus_aos.jar:$APPDIR/lib/tritonus_share.jar:$APPDIR/lib/mp3spi1.9.4.jar:$APPDIR/lib/jl1.0.jar:$APPDIR/lib/jsminim.jar" dreamscape "$@"
